name: API deployment to sbx

on:
  push:
    branches:
      - main
    paths:
      - 'api/**'

jobs:
  update-api-function-code:
    name: Build and deploy API
    runs-on: ubuntu-latest
    environment: SBX

    defaults:
      run:
        shell: bash
        working-directory: api

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2.1.4

      - name: Build
        run: yarn build

      - name: Prepare function
        run: |
          cp package.json build/package.json

      - name: Package function
        working-directory: api/build
        run: zip -rq code.zip ./*

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy
        working-directory: api/build
        run: |
          aws lambda update-function-code --function-name arn:aws:lambda:us-east-1:965776723730:function:githubwzrd-repos --zip-file fileb://./code.zip
          aws lambda update-function-code --function-name arn:aws:lambda:us-east-1:965776723730:function:githubwzrd-me --zip-file fileb://./code.zip
          aws lambda update-function-code --function-name arn:aws:lambda:us-east-1:965776723730:function:githubwzrd-docs --zip-file fileb://./code.zip
