name: Web client deployment to sbx

on:
  push:
    branches:
      - main
    paths:
      - 'client/**'

jobs:
  deploy-web-client:
    name: Build and deploy web cleint
    runs-on: ubuntu-latest
    environment: SBX

    defaults:
      run:
        shell: bash
        working-directory: client

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2.1.4

      - name: Installation of dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy
        working-directory: ./client/build
        run: aws s3 sync . s3://sbx.githubwzrd.xyz --acl bucket-owner-full-control
