name: PR checks for API

on:
  pull_request:
    paths:
      - 'api/**'

jobs:
  pr-check-api:
    name: Vet the pull request
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: api

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2.1.4

      - name: Installation of dependencies
        run: yarn

      - name: Build
        run: yarn build
