name: PR checks for web cleint

on:
  pull_request:
    paths:
      - 'client/**'

jobs:
  pr-check-web-client:
    name: Vet the pull request
    runs-on: ubuntu-latest
    environment: SBX

    defaults:
      run:
        shell: bash
        working-directory: client

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2.1.4

      - name: Installation of dependencies
        run: yarn
